apiVersion: sample.k8s-controller.ad/v1
kind: MyResource
metadata:
  labels:
    app.kubernetes.io/name: k8s-controller-simple
    app.kubernetes.io/managed-by: kustomize
  name: myresource-sample
spec:
  # TODO(user): Add fields here
